source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'sinatra'
gem 'sinatra-reloader'
gem 'haml'
gem 'foreman'
gem 'chartkick'

gem 'data_mapper'
gem 'descriptive_statistics'

group :twitter do
  gem 'chatterbot', :require => 'chatterbot/dsl'
  gem 'rufus-scheduler', :require => 'rufus/scheduler'
end

gem 'sinatra-assetpack', \
  :require => 'sinatra/assetpack', \
  :git => 'git://github.com/rstacruz/sinatra-assetpack.git'

group :development do
  gem 'dm-sqlite-adapter'
end

group :production do
  gem 'dm-postgres-adapter'
end

group :test do
  gem 'rspec'
  gem 'webrat'
  gem 'rack-test', :require => 'rack/test'
end
