source 'http://rubygems.org'
source 'http://gems.github.com'

gem "sinatra"
gem "sinatra-reloader"
gem "haml"
gem "ohm"
gem "foreman"

group :twitter do
  gem "chatterbot", :require => 'chatterbot/dsl'
end

gem 'sinatra-assetpack', \
  :require => 'sinatra/assetpack', \
  :git => 'git://github.com/rstacruz/sinatra-assetpack.git'

group :test do
  gem "rspec"
  gem "webrat"
  gem "rack-test", :require => "rack/test"
end
