desc "start application console"
task :console do
  require 'irb'
  load 'environment.rb'
  ARGV.clear
  IRB.start
end

desc "run specs"
task :spec do
  sh 'rspec'
end

namespace :db do
  desc "seed the database with informatione"
  task :seed do
  end

  desc "drop"
  task :drop do
    load 'environment.rb'
    Ohm.flush
  end
end
