desc "start application console"
task :console do
  require 'irb'
  load 'environment.rb'
  ARGV.clear
  IRB.start
end

desc "run specs"
task :spec do
  sh 'rspec'
end

namespace :db do
  desc "seed the database with informatione"
  task :seed do
  end

  desc "drop"
  task :drop do
    load 'environment.rb'
    Ohm.flush
  end

  desc "dumps measurements to csv"
  task :dump do
    load 'environment.rb'
    puts 'temperature,humidity,timestamp'
    Measurement.all.each do |m|
      puts "#{m.temperature},#{m.humidity},#{m.timestamp}"
    end
  end
end
